// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATuxM-vAD4fxYrqM0poAKz2b_9y95Ci-Y',
    appId: '1:798815628449:web:92ab81ee1b5d0463e614e0',
    messagingSenderId: '798815628449',
    projectId: 'chat-app-c3d75',
    authDomain: 'chat-app-c3d75.firebaseapp.com',
    storageBucket: 'chat-app-c3d75.firebasestorage.app',
    measurementId: 'G-FPRYZBVP1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZs5I9HKQ4dCHK2ERDDPKOP6BTeBfNpps',
    appId: '1:798815628449:android:756d06716ec94e11e614e0',
    messagingSenderId: '798815628449',
    projectId: 'chat-app-c3d75',
    storageBucket: 'chat-app-c3d75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2rYI8VNdAqsQNqEOJuYcWsliW-l0bSBk',
    appId: '1:798815628449:ios:8ec85ae27e1752eee614e0',
    messagingSenderId: '798815628449',
    projectId: 'chat-app-c3d75',
    storageBucket: 'chat-app-c3d75.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2rYI8VNdAqsQNqEOJuYcWsliW-l0bSBk',
    appId: '1:798815628449:ios:8ec85ae27e1752eee614e0',
    messagingSenderId: '798815628449',
    projectId: 'chat-app-c3d75',
    storageBucket: 'chat-app-c3d75.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATuxM-vAD4fxYrqM0poAKz2b_9y95Ci-Y',
    appId: '1:798815628449:web:d67c2757b8467a64e614e0',
    messagingSenderId: '798815628449',
    projectId: 'chat-app-c3d75',
    authDomain: 'chat-app-c3d75.firebaseapp.com',
    storageBucket: 'chat-app-c3d75.firebasestorage.app',
    measurementId: 'G-S1XWH011YG',
  );
}
